[aws]
disabled = true

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

# [git_branch]
# symbol = "ğŸŒ± "

[nodejs]
format = "via [ğŸ‘¾ $version](bold green) "

[env_var]
variable = "SHELL_ARCH"
style = "bold yellow"
format = "[$env_value]($style) "
